#!/usr/bin/python3
from sys import argv

def Factor(n):
    a = n / 2
    a = int(a)+1
    for p in range(1, a):
        for q in range(1, a):
            if p * q == n:
                if p < q:
                    t = p
                    p = q
                    q = t

                print("{}={}*{}".format(n, p, q))


with open(argv[1]) as f:
    for line in f:
        num = int(line)
        Factor(num)
