#!/usr/bin/python3
from sys import argv

def isPrime(n):
    a = n / 2
    a = int(a)+1
    
    if n != 1:
        for p in range(1, a):
            for q in range(1, a):
                if p * q == n:
                    return False
    return True


def RSA(n):
    a = n / 2
    a = int(a)+1
    if n != 1:
        for p in range(1, a):
            if isPrime(p):
                for q in range(1, a):
                    if isPrime(q):
                        if p * q == n:
                            if p < q:
                                t = p
                                p = q
                                q = t

                            print("{}={}*{}".format(n, p, q))
                            return
    print("{}={}*{}".format(n, 1, 1))

with open(argv[1]) as f:
    for line in f:
        num = int(line)
        RSA(num)
